@IsTest
public class ClassATest {
	
    @IsTest
    public static void DoubleNumberTest(){
        
        //ClassA test = new ClassA();
	
        Integer[] result = P0B.rotateLeftNTimes( new Integer[]{3,4}, 5);
        
        /*
        System.assertEquals(2, result);
        result = test.DoubleNumber(5);
        System.assertEquals(10,result);
        result = test.AddNumber(10,10);
        System.assertEquals(20,result);
		*/
    }
}